# Generated by Django 4.2.10 on 2025-01-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('midwifes', models.ManyToManyField(related_name='villages', to='account.midwife')),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.puskesmas')),
            ],
        ),
    ]
