services:
  be-posyandu:
    env_file:
      - .env.prod
    expose:
      - 8000
    volumes:
      - .:/app
    networks:
      - npm-networks

  db-posyandu:
    volumes:
      - postgres_posyandu_prod:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: posyandu_db_prod
      POSTGRES_USER: posyandu_user_prod
      POSTGRES_PASSWORD: Admin123
    networks:
      - npm-networks

networks:
  npm-networks:
    external: true

volumes:
  postgres_posyandu_prod: