services:
  be-posyandu:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app

  db-posyandu:
    volumes:
      - postgres_posyandu_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: posyandu_db_dev
      POSTGRES_USER: posyandu_user_dev
      POSTGRES_PASSWORD: Admin123

volumes:
  postgres_posyandu_dev: