services:
  be-posyandu:
    container_name: be-posyandu
    build: .
    command: sh -c "python3 app/manage.py makemigrations account base && 
                    python3 app/manage.py migrate --no-input && 
                    python3 app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db-posyandu:
    container_name: db-posyandu
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: posyandu
      POSTGRES_USER: posyandu_user
      POSTGRES_PASSWORD: Admin123

volumes:
  postgres_data: