services:
  be-posyandu:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - .:/app
    networks:
      - npm_networks

  db-posyandu:
    volumes:
      - postgres_posyandu:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: posyandu_db_prod
      POSTGRES_USER: posyandu_user_prod
      POSTGRES_PASSWORD: Admin123
    networks:
      - npm_networks

volumes:
  postgres_posyandu:

networks:
  npm_networks:
    external: true