# Generated by Django 4.2.10 on 2024-04-06 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('birth_order', models.PositiveIntegerField()),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('birth_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('kia_number', models.CharField(blank=True, max_length=50, null=True)),
                ('imd_number', models.CharField(blank=True, max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='child_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posyandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puskesmas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosyanduActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posyandu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posyandu')),
            ],
        ),
        migrations.AddField(
            model_name='posyandu',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.village'),
        ),
        migrations.CreateModel(
            name='MidwifeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.village')),
                ('midwife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('head_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.PositiveIntegerField()),
                ('measurement_method', models.CharField(max_length=255)),
                ('arm_circumference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_for_age', models.CharField(max_length=255)),
                ('z_score_weight_for_age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_for_age', models.CharField(max_length=255)),
                ('z_score_height_for_age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_for_height', models.CharField(max_length=255)),
                ('z_score_weight_for_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_gain', models.CharField(max_length=255)),
                ('pmt_received', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitamin_a_count', models.PositiveIntegerField()),
                ('kpsp', models.BooleanField()),
                ('kia', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.child')),
                ('posyandu_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posyanduactivity')),
            ],
        ),
        migrations.CreateModel(
            name='CadreAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posyandu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posyandu')),
            ],
        ),
    ]
