# Generated by Django 4.2.10 on 2024-04-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='kia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='kpsp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='pmt_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='vitamin_a_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_gain',
            field=models.CharField(choices=[('O', 'O'), ('T', 'T')], max_length=1),
        ),
    ]
