# Generated by Django 4.2.10 on 2024-04-06 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_childmeasurement_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='midwifeassignment',
            old_name='Village',
            new_name='village',
        ),
    ]
