# Generated by Django 4.2.10 on 2024-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_posyanduactivity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='national_id_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='posyandu',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
