# Generated by Django 4.2.10 on 2024-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_child_national_id_number_alter_posyandu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='national_id_number',
            field=models.CharField(max_length=50),
        ),
    ]
