# Generated by Django 4.2.10 on 2024-05-02 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_child_national_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPosyandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('posyandu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.posyandu')),
            ],
        ),
    ]
