# Generated by Django 4.2.10 on 2024-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_lengthforageboys_age_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='birth_height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='arm_circumference',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='pmt_received',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='z_score_height_for_age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='z_score_weight_for_age',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='z_score_weight_for_height',
            field=models.FloatField(),
        ),
    ]
