# Generated by Django 4.2.10 on 2024-05-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_childmeasurement_height_for_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.ImageField(upload_to='growth_charts/')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.child')),
            ],
        ),
    ]
