# Generated by Django 4.2.10 on 2024-05-03 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_growthchart_height_for_age_chart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthchart',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.child'),
        ),
    ]
