# Generated by Django 4.2.10 on 2024-05-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_growthchart_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthchart',
            name='height_for_age_chart',
            field=models.ImageField(blank=True, null=True, upload_to='growth_charts/'),
        ),
        migrations.AlterField(
            model_name='growthchart',
            name='legth_for_age_chart',
            field=models.ImageField(blank=True, null=True, upload_to='growth_charts/'),
        ),
        migrations.AlterField(
            model_name='growthchart',
            name='weight_for_age_chart',
            field=models.ImageField(blank=True, null=True, upload_to='growth_charts/'),
        ),
        migrations.AlterField(
            model_name='growthchart',
            name='weight_for_height_chart',
            field=models.ImageField(blank=True, null=True, upload_to='growth_charts/'),
        ),
    ]
