# Generated by Django 4.2.10 on 2024-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_childmeasurement_age_in_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='arm_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(blank=True, choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_gain',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('T', 'T')], max_length=1, null=True),
        ),
    ]
