# Generated by Django 4.2.10 on 2024-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_childmeasurement_arm_circumference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightForAgeBoys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.PositiveSmallIntegerField(unique=True, verbose_name='Umur (bulan)')),
                ('sd_minus_3', models.FloatField(verbose_name='-3 SD')),
                ('sd_minus_2', models.FloatField(verbose_name='-2 SD')),
                ('sd_minus_1', models.FloatField(verbose_name='-1 SD')),
                ('median', models.FloatField(verbose_name='Median')),
                ('sd_plus_1', models.FloatField(verbose_name='+1 SD')),
                ('sd_plus_2', models.FloatField(verbose_name='+2 SD')),
                ('sd_plus_3', models.FloatField(verbose_name='+3 SD')),
            ],
        ),
        migrations.CreateModel(
            name='WeightForAgeGirls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.PositiveSmallIntegerField(unique=True, verbose_name='Umur (bulan)')),
                ('sd_minus_3', models.FloatField(verbose_name='-3 SD')),
                ('sd_minus_2', models.FloatField(verbose_name='-2 SD')),
                ('sd_minus_1', models.FloatField(verbose_name='-1 SD')),
                ('median', models.FloatField(verbose_name='Median')),
                ('sd_plus_1', models.FloatField(verbose_name='+1 SD')),
                ('sd_plus_2', models.FloatField(verbose_name='+2 SD')),
                ('sd_plus_3', models.FloatField(verbose_name='+3 SD')),
            ],
        ),
    ]
