# Generated by Django 4.2.10 on 2024-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_weightforageboys_weightforagegirls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_age_chart',
            new_name='weight_for_age_chart_0_24',
        ),
        migrations.AddField(
            model_name='growthchart',
            name='weight_for_age_chart_24_60',
            field=models.ImageField(blank=True, null=True, upload_to='growth_charts/'),
        ),
    ]
