# Generated by Django 4.2.10 on 2024-05-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_weight_for_age_chart_growthchart_weight_for_age_chart_0_24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posyanduactivity',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='posyanduactivity',
            name='name',
            field=models.CharField(default='Kegiatan Posyandu', max_length=255),
        ),
    ]
