# Generated by Django 4.2.10 on 2024-05-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_parentprofile_posyandu'),
        ('base', '0028_alter_child_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentposyandu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.parent'),
        ),
    ]
