# Generated by Django 4.2.10 on 2024-05-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_parentprofile_posyandu'),
        ('base', '0029_alter_parentposyandu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadreassignment',
            name='cadre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cadre'),
        ),
    ]
