# Generated by Django 4.2.10 on 2024-05-06 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_parentprofile_posyandu'),
        ('base', '0030_alter_cadreassignment_cadre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midwifeassignment',
            name='midwife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.midwife'),
        ),
    ]
