# Generated by Django 4.2.10 on 2024-05-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_midwifeassignment_midwife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='posyandu_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.posyanduactivity'),
        ),
    ]
