# Generated by Django 4.2.10 on 2024-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_anthropometricstandard_delete_heightforageboys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anthropometricstandard',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
