# Generated by Django 4.2.10 on 2024-05-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_anthropometricstandard_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anthropometricstandard',
            name='gender',
        ),
    ]
