# Generated by Django 4.2.10 on 2024-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_remove_anthropometricstandard_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='imd_number',
        ),
        migrations.RemoveField(
            model_name='child',
            name='kia_number',
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='height_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_gain',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
