# Generated by Django 4.2.10 on 2024-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_remove_child_imd_number_remove_child_kia_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], default=0, max_length=8),
            preserve_default=False,
        ),
    ]
