# Generated by Django 4.2.10 on 2024-05-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_childmeasurement_head_circumference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8, null=True),
        ),
    ]
