# Generated by Django 4.2.10 on 2024-05-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_childmeasurement_head_circumference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthchart',
            old_name='height_for_age_24_60_chart',
            new_name='height_for_age_chart',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='legth_for_age_0_24_chart',
            new_name='legth_for_age_chart',
        ),
    ]
