# Generated by Django 4.2.10 on 2024-05-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_height_for_age_24_60_chart_growthchart_height_for_age_chart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthchart',
            old_name='legth_for_age_chart',
            new_name='length_for_age_chart',
        ),
    ]
