# Generated by Django 4.2.10 on 2024-06-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_legth_for_age_chart_growthchart_length_for_age_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmeasurement',
            name='kia',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='kpsp',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='pmt_received',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='vitamin_a_count',
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='bmi_for_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='z_score_bmi_for_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='height_for_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_height',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
