# Generated by Django 4.2.10 on 2024-06-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_remove_childmeasurement_kia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmeasurement',
            name='arm_circumference',
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='bmi_for_age',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='height_for_age',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_age',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_height',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
