# Generated by Django 4.2.10 on 2024-09-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_remove_childmeasurement_arm_circumference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='bmi_for_age',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='height_for_age',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_age',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_height',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
    ]
