# Generated by Django 4.2.10 on 2024-12-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_childmeasurement_bmi_for_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childmeasurement',
            options={'ordering': ['-age_in_month']},
        ),
    ]
