# Generated by Django 4.2.10 on 2025-01-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posyandu', '0001_initial'),
        ('village', '0001_initial'),
        ('base', '0045_alter_childmeasurement_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='puskesmas',
        ),
        migrations.AlterField(
            model_name='cadreassignment',
            name='posyandu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu'),
        ),
        migrations.AlterField(
            model_name='midwifeassignment',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village'),
        ),
        migrations.AlterField(
            model_name='parentposyandu',
            name='posyandu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu'),
        ),
        migrations.AlterField(
            model_name='posyanduactivity',
            name='posyandu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu'),
        ),
        migrations.DeleteModel(
            name='Posyandu',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
    ]
