# Generated by Django 4.2.10 on 2025-01-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_village_puskesmas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='child',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='posyandu_activity',
        ),
        migrations.RemoveField(
            model_name='posyanduactivity',
            name='posyandu',
        ),
    ]
