# Generated by Django 4.2.10 on 2025-01-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('base', '0047_remove_child_parent_remove_childmeasurement_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthchart',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='child.child'),
        ),
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='ChildMeasurement',
        ),
        migrations.DeleteModel(
            name='PosyanduActivity',
        ),
    ]
