# Generated by Django 4.2.10 on 2025-01-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posyandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadres', models.ManyToManyField(related_name='cadre_posyandus', to='account.cadre')),
                ('parents', models.ManyToManyField(related_name='parent_posyandus', to='account.parent')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='village.village')),
            ],
        ),
    ]
