# Generated by Django 4.2.10 on 2025-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('posyandu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posyandu',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='posyandus', to='account.parent'),
        ),
    ]
