# Generated by Django 4.2.10 on 2025-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('posyandu', '0003_posyandu_cadres_alter_posyandu_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posyandu',
            name='parents',
            field=models.ManyToManyField(related_name='parent_posyandus', to='account.parent'),
        ),
    ]
