# Generated by Django 4.2.10 on 2025-01-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posyandu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosyanduActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kegiatan Posyandu', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posyandu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posyandu.posyandu')),
            ],
        ),
    ]
