# Generated by Django 4.2.10 on 2025-01-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posyandu_activity', '0001_initial'),
        ('child', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropometricStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.FloatField()),
                ('sd_minus_3', models.FloatField()),
                ('sd_minus_2', models.FloatField()),
                ('sd_minus_1', models.FloatField()),
                ('median', models.FloatField()),
                ('sd_plus_1', models.FloatField()),
                ('sd_plus_2', models.FloatField()),
                ('sd_plus_3', models.FloatField()),
                ('measurement_type', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Laki-laki'), ('F', 'Perempuan')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_for_age_chart_0_24', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('weight_for_age_chart_24_60', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('length_for_age_chart_0_24', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('height_for_age_chart_24_60', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('weight_for_length_chart_0_24', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('weight_for_height_chart_24_60', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('bmi_for_age_chart_0_24', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('bmi_for_age_chart_24_60', models.ImageField(blank=True, null=True, upload_to='growth_charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='child.child')),
            ],
        ),
        migrations.CreateModel(
            name='ChildMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('head_circumference', models.FloatField(blank=True, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('age_in_month', models.PositiveIntegerField(blank=True, null=True)),
                ('measurement_method', models.CharField(blank=True, choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8, null=True)),
                ('arm_circumference', models.FloatField(blank=True, null=True)),
                ('weight_for_age', models.CharField(blank=True, max_length=255, null=True)),
                ('z_score_weight_for_age', models.FloatField(blank=True, null=True)),
                ('height_for_age', models.CharField(blank=True, max_length=255, null=True)),
                ('z_score_height_for_age', models.FloatField(blank=True, null=True)),
                ('weight_for_height', models.CharField(blank=True, max_length=255, null=True)),
                ('z_score_weight_for_height', models.FloatField(blank=True, null=True)),
                ('weight_gain', models.CharField(blank=True, choices=[('O', 'O'), ('T', 'T')], max_length=1, null=True)),
                ('pmt_received', models.FloatField(blank=True, null=True)),
                ('vitamin_a_count', models.PositiveIntegerField(blank=True, null=True)),
                ('kpsp', models.BooleanField(blank=True, null=True)),
                ('kia', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='child.child')),
                ('posyandu_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posyandu_activity.posyanduactivity')),
            ],
        ),
    ]
