# Generated by Django 4.2.10 on 2025-01-01 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child_measurement', '0001_initial'),
        ('posyandu_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmeasurement',
            name='posyandu_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posyandu_activity.posyanduactivity'),
        ),
    ]
