# Generated by Django 4.2.10 on 2025-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmeasurement',
            name='head_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
