# Generated by Django 4.2.10 on 2025-01-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_measurement', '0003_rename_height_for_age_chart_growthchart_height_for_age_24_60_chart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmeasurement',
            name='bmi_for_age',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='height_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='weight_for_height',
            field=models.CharField(blank=True, default='normal', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='weight_gain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='z_score_bmi_for_age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='z_score_weight_for_height',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
