# Generated by Django 4.2.10 on 2025-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child_measurement', '0004_childmeasurement_bmi_for_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childmeasurement',
            options={},
        ),
        migrations.RenameField(
            model_name='childmeasurement',
            old_name='height_gain',
            new_name='arm_circumference',
        ),
        migrations.RenameField(
            model_name='childmeasurement',
            old_name='z_score_bmi_for_age',
            new_name='pmt_received',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='bmi_for_age_0_24_chart',
            new_name='bmi_for_age_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='bmi_for_age_24_60_chart',
            new_name='bmi_for_age_24_60',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='height_for_age_24_60_chart',
            new_name='height_for_age_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='length_for_age_0_24_chart',
            new_name='length_for_ag_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_age_0_24_chart',
            new_name='weight_for_age_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_age_24_60_chart',
            new_name='weight_for_age_24_60',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_height_24_60_chart',
            new_name='weight_for_height_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_length_0_24_chart',
            new_name='weight_for_length_0_24',
        ),
        migrations.RemoveField(
            model_name='childmeasurement',
            name='bmi_for_age',
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='kia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='kpsp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childmeasurement',
            name='vitamin_a_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='height_for_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='measurement_method',
            field=models.CharField(blank=True, choices=[('STANDING', 'Standing'), ('SUPINE', 'Supine')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_for_height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='childmeasurement',
            name='weight_gain',
            field=models.CharField(blank=True, choices=[('O', 'O'), ('T', 'T')], max_length=1, null=True),
        ),
    ]
