# Generated by Django 4.2.10 on 2025-01-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_measurement', '0005_alter_childmeasurement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthchart',
            old_name='bmi_for_age_0_24',
            new_name='bmi_for_age_chart_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='bmi_for_age_24_60',
            new_name='bmi_for_age_chart_24_60',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='height_for_age_0_24',
            new_name='height_for_age_chart_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='length_for_ag_0_24',
            new_name='length_for_age_chart_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_age_0_24',
            new_name='weight_for_age_chart_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_age_24_60',
            new_name='weight_for_age_chart_24_60',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_height_0_24',
            new_name='weight_for_height_chart_0_24',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_length_0_24',
            new_name='weight_for_length_chart_0_24',
        ),
    ]
