# Generated by Django 4.2.10 on 2025-01-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('child_measurement', '0006_rename_bmi_for_age_0_24_growthchart_bmi_for_age_chart_0_24_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='growthchart',
            old_name='height_for_age_chart_0_24',
            new_name='height_for_age_chart_24_60',
        ),
        migrations.RenameField(
            model_name='growthchart',
            old_name='weight_for_height_chart_0_24',
            new_name='weight_for_height_chart_24_60',
        ),
    ]
