# Generated by Django 4.2.10 on 2024-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('MIDWIFE', 'Midwife'), ('PARENT', 'Parent'), ('CADRE', 'Cadre')], max_length=10),
        ),
    ]
