# Generated by Django 4.2.10 on 2025-01-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='validated',
        ),
    ]
