# Generated by Django 4.2.10 on 2024-04-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_child_national_id_number'),
        ('account', '0002_alter_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='posyandu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.posyandu'),
        ),
    ]
