# Generated by Django 4.2.10 on 2024-05-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_parentprofile_posyandu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='posyandu',
        ),
    ]
