# Generated by Django 4.2.10 on 2024-05-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_parentprofile_posyandu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puskesmasprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
