# Generated by Django 4.2.10 on 2025-01-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
